name: Cargo Build, Test, Format, and Clippy

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  formatting:
    name: Rust project - Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install rustfmt
        run: rustup component add rustfmt
      - name: Check formatting
        run: cargo fmt --all -- --check

  clippy:
    name: Rust project - Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Clippy
        run: rustup component add clippy
      - name: Run Clippy
        run: cargo clippy --all -- -D warnings

  build_and_test:
    name: Rust project - Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --all --verbose
      - run: cargo test --all --verbose

